### ISSUE TITLE
Unable to load iDigBio index from Elastic Search as a dataframe

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-datasets#3]
When trying to load the current index from prod using the elastic.co elasticsearch-hadoop connector in Spark, I get:

```
 File "/opt/spark/latest/python/lib/py4j-0.10.1-src.zip/py4j/protocol.py", line 312, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o31.load.
: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unknown GeoShape [null]
```

I found this closed issue https://github.com/elastic/elasticsearch-hadoop/issues/607 which describes the problem. It sounds like a key part of the fix is that they sample some of the data in the GeoShape field to determine the type. The SQL interface in Spark is strongly typed so they need to know the structure **and** the structure has to stay the same for all rows. 

I remember you said that the field is actually empty. Is that the "[null]" part of the error I'm seeing? Is the issue that there is no data to sample?

The work-around is to load everything as an RRD, create a structure definition (and possibly drop or reformat columns) and then create a df passing in the definition. That's 5-50 lines of code depending on how automatic I get with the structure def.

**Comment by godfoder** [comment]
Should be fixed in the next version of the indexes that I build, 2.10.2.

**Comment by mjcollin** [comment]
Special non-derministic columns are excluded or handled by hand now. The parquet check notebook also includes some code to help find fields that cause parquet builds to break so when @godfoder adds new ones (like associatedsequences) they're easy to find. See https://github.com/bio-guoda/guoda-datasets/blame/master/iDigBio/es_load_job.py#L36
